app/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views
from django.utils.translation import gettext_lazy as _

app_name = 'app'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path(_('about/'), views.AboutUsView.as_view(), name='about'),
    path(_('new/'), views.NewsView.as_view(), name='new'),
    path(_('women/'), views.WomenView.as_view(), name='women'),
    path(_('girls/'), views.NewsView.as_view(), name='girls'),
    path(_('contact/'), views.ContactView.as_view(), name='contact'),
    path(_('register/'), views.register, name='register'),
    path(_('product_list/'), views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('product_list/<slug:id>/', views.product_detail, name='product_detail'),

]

charaproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _

urlpatterns = i18n_patterns(
    path(_('admin/'), admin.site.urls),
    path('', include('app.urls', namespace='app')),
    # path(_('account/'), include('app.urls')),
    path('account/', include('django.contrib.auth.urls'))

)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/products/detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}{{ product.name }}{% endblock %}

{% block content%}

    <div class="product-detail">
        <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/accessories-bg.png" %}{% endif %}">
        <h1>{{ product.name }}</h1>
        <h2>
{#            <a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a>#}
        </h2>
        <p class="price">${{ product.price }}</p>
        {{ product.description|linebreaks }}
    </div>
{% endblock %}

templates/products/list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    {% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}

{% block content %}
    <div id="sidebar">
    <h3>Categories</h3>
    <ul>
        <li {% if not category %}class="selected"{% endif %}>
            <a href="{% url "app:product_list" %}">All</a>
        </li>
        {% for c in categories %}
            <li {% if category.slug == c.slug %}class="selected"
            {% endif %}>
                <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
            </li>
        {% endfor %}
    </ul>
    </div>
    <div id="main" class="product-list">
        <h1>{% if category %}{{ category.name }}{% else %}Products{% endif %}</h1>
        {% for product in products %}
            <div class="item">
                <a href="{% url 'app:product_detail' product.slug %}"><img src="{% if product.image %}{{ product.image.url }}{%else %}{% static "img/no_image.png" %}{% endif %}"></a>
                <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
                <br>
                ${{ product.price }}
            </div>
        {% endfor %}
    </div>
{% endblock content %}